volumes:
  db:
  redis_data:

services:
  db:
    image: postgres:17.2
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure

  redis:
    image: redis:7
    container_name: redis_service
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: on-failure

  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8001:8001"


  calendar_service:
    build:
      context: .
      dockerfile: calendar_service/Dockerfile
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8002:8002"


  meeting_service:
    build:
      context: .
      dockerfile: meeting_service/Dockerfile
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8003:8003"


  task_service:
    build:
      context: .
      dockerfile: task_service/Dockerfile
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8004:8004"


  team_service:
    build:
      context: .
      dockerfile: team_service/Dockerfile
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8005:8005"


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - calendar_service
      - meeting_service
      - task_service
      - team_service
    restart: on-failure




