volumes:
  db:
  redis_data:

networks:
  backend:

services:
  db:
    image: postgres:17.2
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7
    container_name: redis_service
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always
    depends_on:
      - db
    restart: always

  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend
    restart: always

  calendar_service:
    build:
      context: .
      dockerfile: calendar_service/Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend
    restart: always

  meeting_service:
    build:
      context: .
      dockerfile: meeting_service/Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend
    restart: always

  task_service:
    build:
      context: .
      dockerfile: task_service/Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend
    restart: always

  team_service:
    build:
      context: .
      dockerfile: team_service/Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - calendar_service
      - meeting_service
      - task_service
      - team_service
    networks:
      - backend
    restart: always




